### ISSUE TITLE
Suggestion: Put the syntax as a prop

### ISSUE THREAD

**Issue by bryanaf7** [Joeyonng/react-jupyter-notebook#1]
Hello, thanks a lot for sharing this amazing tool. I added it into a portfolio template website and it came out amazing. After fiddling around with the build code, I found the place in your code to choose which syntax to use. After messing with that and the background, I got the exact visual that I wanted. Could you please put which syntax to use as a prop for the component? [Here are the list for the prism syntax colors.](https://github.com/react-syntax-highlighter/react-syntax-highlighter/blob/HEAD/AVAILABLE_STYLES_PRISM.MD) I can't thank you enough for this share.

**Comment by Joeyonng** [comment]
Hi bryanaf7,

Thanks for your suggestion and sorry for the late reply! I will try to implement this feature these days.

**Comment by Joeyonng** [comment]
Hi bryanaf7:

I think my recent commit d4a0dcf implements this feature. However, I switch from prism.js to highlight.js for `react-syntax-highlighter` since prism.js with `react-syntax-highlighter` has some bugs. Please see https://github.com/Joeyonng/react-jupyter-notebook#customising-code-block-styles-codeblockstyles-prop for details.
